### ISSUE TITLE
Problem installing crud-view and its dependencies

### ISSUE THREAD

**Issue by jconlon** [manolo/crud-view#1]
Have a problem installing the crud-view and its dependencies with bower:
`
$ bower install --save crud-view
bower crud-view#*               cached https://github.com/manolo/crud-view.git#1.0.2

bower crud-view#*             validate 1.0.2 against https://github.com/manolo/crud-view.git#*

bower starter-elements#^0.0.5       not-cached https://github.com/vaadin/starter-elements.git#^0.0.5

bower starter-elements#^0.0.5          resolve https://github.com/vaadin/starter-elements.git#^0.0.5

Username for 'https://github.com': jconlon
Password for 'https://jconlon@github.com': 

bower starter-elements#^0.0.5          ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/vaadin/starter-elements.git", exit code of #128 remote: 

Repository not found. fatal: repository 'https://github.com/vaadin/starter-elements.git/' not found
`

**Comment by manolo** [comment]
Updated the repo bringing back a set of elements that are not available anymore.
Let me know if it works for you

**Comment by jconlon** [comment]
That did it. Thanks!
